wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
batch_size:
  desc: null
  value: 64
beta_frames:
  desc: null
  value: 50000
beta_start:
  desc: null
  value: 0.4
buffer_capacity:
  desc: null
  value: 100000
eps_decay:
  desc: null
  value: 5000
eps_end:
  desc: null
  value: 0.01
gamma:
  desc: null
  value: 0.99
hidden_dims:
  desc: null
  value: 32
lr:
  desc: null
  value: 1.0e-05
n_batches_per_epoch:
  desc: null
  value: 100
n_epochs:
  desc: null
  value: 1
n_steps:
  desc: null
  value: 3
update_interval:
  desc: null
  value: 25000
